BLOCKCHAIN-161 - Referendum concerning Constitution - verify tallying
liberland/liberland_substrate pull request #325
Opened 2023-09-19 13:20 UTC by MichalLustykNeti

2023-09-20 10:05 UTC, kacperzuk-neti requested changes
What about Frontend, does it handle this threshold in any way?
If it does, does it already expect 2/3 or is there a PR to fix it?
If it doesn't, can you create a JIRA issue for that? I guess it should at least be handled somehow on the list of referendum, where it shows if it currently has enough votes to pass or not.

2023-09-20 14:52 UTC, MichalLustykNeti commented
> What about Frontend, does it handle this threshold in any way? If it does, does it already expect 2/3 or is there a PR to fix it? If it doesn't, can you create a JIRA issue for that? I guess it should at least be handled somehow on the list of referendum, where it shows if it currently has enough votes to pass or not.

Done task on JIRA created 

https://liberland.atlassian.net/jira/software/projects/BLOCKCHAIN/boards/2?selectedIssue=BLOCKCHAIN-210

2023-09-22 14:38 UTC, kacperzuk-neti approved these changes

2023-10-05 10:45 UTC, DorianSternVukotic approved these changes

2023-10-05 10:45 UTC, merged