BLOCKCHAIN-175 Multiple referenda per LaunchPeriod
liberland/liberland_substrate pull request #332
Opened 2023-09-29 14:55 UTC by MichalLustykNeti

2023-09-29 15:00 UTC, kacperzuk-neti approved these changes

2023-10-05 10:57 UTC, DorianSternVukotic requested changes
Need to confirm that ALL proposals become referendums as a requirement

2023-10-31 15:09 UTC, MichalLustykNeti commented
> Need to confirm that ALL proposals become referendums as a requirement
Here is screen that show launching all proposals. To test it i set `pub const LaunchPeriod: BlockNumber = 10;` to make launching much faster.

![image](https://github.com/liberland/liberland_substrate/assets/133770876/2d8ec765-416a-4dac-8432-deade53a3756)
![image](https://github.com/liberland/liberland_substrate/assets/133770876/244faa42-b9c4-4612-ab68-4336d88a04ef)

2023-11-17 14:27 UTC, DorianSternVukotic commented
Is is a requirement, that has some risks, YOLO

2023-11-17 14:27 UTC, merged