BLOCKCHAIN-187 - Senate Veto during Enactment Period
liberland/liberland_substrate pull request #334
Opened 2023-10-12 12:05 UTC by MichalLustykNeti

2023-10-19 09:03 UTC, kacperzuk-neti requested changes
Doesn't work for me.
![image](https://github.com/liberland/liberland_substrate/assets/117277751/75bc2f9d-88c3-4821-ac6f-ca56681a3d26)
How should I test it to make it work?

2023-10-19 09:04 UTC, kacperzuk-neti commented
Fix commit msg.

2023-10-31 14:39 UTC, kacperzuk-neti approved these changes

2023-11-09 00:01 UTC, DorianSternVukotic approved these changes

2023-11-09 12:49 UTC, merged