Blockchain 423 substrate remove unnecessary pallets
liberland/liberland_substrate pull request #366
Opened 2024-04-12 14:18 UTC by MichalLustykNeti

2024-04-12 14:27 UTC, kacperzuk-neti requested changes

2024-04-12 14:27 UTC, kacperzuk-neti commented on substrate/bin/node/runtime/src/migrations.rs
> -                weight = weight.saturating_add(DbWeight::get().reads_writes(1, 1));
Just drop the whole migration, we won't need it anymore.

2024-04-12 15:46 UTC, kacperzuk-neti commented
Did you fork-test and try-runtime test it maybe?

2024-04-15 12:11 UTC, MichalLustykNeti commented
> Did you fork-test and try-runtime test it maybe?

![image](https://github.com/liberland/liberland_substrate/assets/133770876/f3ac3b4e-88ea-4ecc-bec0-29170cc039a3)

2024-04-16 23:07 UTC, merged